# Common paths
data_path: 'DATA' #'/home/achernikov/CLS/DATA'
datasets_dir: 'datasets'
images_dir: 'pictures'
masks_dir: 'masks'
meta_dir: 'meta'
models_dir: 'models'

test_path: 'TEST' #'/home/achernikov/CLS/TEST'
test_masks_dir: 'masks'
infer_dir: 'infer2'

