# Common paths
data_path: '/home/achernikov/CLS/DATA'
datasets_dir: 'datasets'
images_dir: 'pictures'
masks_dir: 'masks'
meta_dir: 'meta'
models_dir: 'models'

# Train paths
#background_dataset_path: 'datasets/background.json'
dataset_path: 'datasets/tits_size.json'
badlist_path: 'badlists/tits_size_badlist.txt'

# additional_background_dir: ''




