version: "3.8"

services:
  web:
    build: .
    command: poetry run uvicorn cls.testing.app:app --host 0.0.0.0 --port 8080 # > /app/logs/fastapi.log
    ports:
      - ${FASTAPI_PORT}:8080
    volumes:
      - ./logs:/app/logs
      - ./data_testing2:/app/data_testing2
      - ./people_models:/app/people_models
      - /data/achernikov/workspace/CLS/DATA:/data/achernikov/workspace/CLS/DATA
    env_file: ./.env
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    depends_on:
      - worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    
  worker:
    build: .
    command: celery -A cls.testing.worker worker --loglevel=INFO --logfile=/app/logs/celery.log
    env_file: ./.env
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    volumes:
      - ./logs:/app/logs
      - ./data_testing2:/app/data_testing2
      - ./people_models:/app/people_models
      - /data/achernikov/workspace/CLS/DATA:/data/achernikov/workspace/CLS/DATA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - redis

  redis:
    image: redis:7
  
  # rabbitmq:
  #   image: rabbitmq
  #   networks:
  #     - cls_net

# networks:
#   cls_net:
#     driver: bridge



