name: Docs

on:
  push:
    branches: [ main ]

permissions:
    contents: write

jobs:
  docs-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
